import { TestBed } from '@angular/core/testing';

import { BatchedOps } from './batched-ops';

/**
 * Note:
 * `BatchedOps` is not decorated with Angular `@injectable` because we want to instantiate it ourselves ouside of Angular DI.
 * @todo the test below was autogenerated as part of angular `service` schematics, but `BatchedOps` is not an angular service anymore.
 * Need to modify these tests when adding new tests to this file later
 */

describe('BatchedOps', () => {
  let service: BatchedOps;

  beforeEach(() => {
    TestBed.configureTestingModule({});
    service = TestBed.inject(BatchedOps);
  });

  it('should be created', () => {
    expect(service).toBeTruthy();
  });
});
